language: ruby
rvm:
- 2.4.1
script: "./bin/cibuild"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: YA5KByVGjIAC1kuz8aXcJq1VwUqb/Iy4r5GnRljWBAokpLdpr3SU02jAwD2OhiQrgeEaHR17ratMZ0BFGv7XTihyvGahzWaNno2jgbBow4m3CfGN9G2Z885L5QwSEkmiajNo8jx3a2N56OK4mMet2aNZQ9UjzQE6C2mT0yqntXLiFmF/+43Y6IpM3cXWw0ZC5x+c48bDhp8TDNgFpYCWLQC5ubombnh0etYXS7yUjHAK6wlh1HhcBa8xltoF0ZIn7GpZ8YAUe6blMgyLoe+T+Q/TmtxFjTWJnOqw/CHkOGEjT0MWu9+v3n7k7pQXzbYCeUA7jjTZknYbkvhpa2Bnqim2KOEgTNUBbIecML1+q1YcMvpKARReHXaWyYLFf4AmjfwS6HaAKE1V3gP3ebfuF0x6+CJ8Gkj7cagxTeUiOLKijU/raNJAkbKt7zHzF1oJf/Fy0mf8pwKFc9dNNYSJhP5vr7A4Eq+dkJi4wXLC84C3X0pm6rAqnOEiDK5mmmRKaoIYc+GTMMzLP+tF3hsx55klQucnX3XwMPMvmz2MMiFt2EqdJZm0SyT+fiSgzilnL0YTMzl1iKTsG8dL6kcd0SF2FqLjPJRD3Q2CRUCZXqbWLiWQdGgF7bN00LrYlK+8PXoP5z7L94bP2q6dYJy/dzVi/bWAhb/msE0n2ZkKBS0=
sudo: false
cache: bundler
notifications:
  email: false

after_script:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - node ./node_modules/grunt-cli/bin/grunt release
  - yes | ./bin/deploy
