dist: xenial
language: ruby

rvm:
- 2.4.1

before_install:
- yes | bundle update
- yes | sudo apt install libmagick++-dev
- yes | gem install rmagick exifr

addons:
  apt:
    update: true

env:
  global:
    secure: VC21IhOnWRDQt/P0iG/riUh9B/gfG04zL0Gussl+dUzxjIn3B1Y9Pu9+T/ZfsFS9arxKkxFcTqtQkCPtlhV0EIvP4rDMrDV+RLRpWYAEdprk8c0UDGwHtUK3k5AZRJThRmxyRKD+t04lc6+4brriMruZRXOhClpVnfwMyYkQIAsICnDRXlSSv9F83ZYe52HdtZNjx9KEYBYTmBcfX3tPKoFLJUsdwICRV1KBmIp8xKRwBhHtLAL5cGBUrmvye4BLoIIwXJ0wwmEtqC8y0v7HSBhvammDJlgCO/3Xb0x+091QrkD6Y4amWLik+a/o3JTgHQC+wFTFQH8QgKjOs2K5C3A8X/xH7UcoWiDsMU7rUZf8Pa8uo/Dh/i041atOIcDtD/MySVawsPIl/KJY3yRL/svMzakoYW09kWlmvdsrbhkP9yjckWX5HGwKV9iODmpkRCypI1rO52xY2UeN8/Bvk+7BVoQRldR0jxjRGQmshVd2Okv8UB+DOX/dbonM+B7AsG/0JsjJfMFtZIx7s5h71PYFKMAfz4CMO/SSbZ3dyJSlFRQBvHTL2R+7PgFIJZMgrzrlMvalgBbRID2Aj2bEi5797iIHF3/bfU1KV+3FWhxUjJV9uqOneuqAPn0T5Y4BAgfSfymogbQ0TzyRKFhU3OUfpIGT5IrbzbNLSmh2KyQ=

script: "./bin/cibuild"
sudo: false
cache: bundler
notifications:
  email: false

after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
- yes | ./bin/deploy
