
title: Daniel Andrade Photo Gallery
email: daniel@danielandrade.net
description: >- # this means to ignore newlines until "baseurl:"
  My own little photo gallery
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dspillere
github_username:  dansku

# Build settings
markdown: kramdown


#--------------------------------------------
gallery:
  dir: photos
  title: "Photos"
  sort_field: "date"
  title_prefix: "" 
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  thumbnail_size:
    y: 400
    x: 400
    retina: 1.5
    
  # The following options are for individual galleries.
  galleries:
    2017_Istanbul:
      name: "Istanbul"
      date: "2017/01/01"
      best_image: 0011.jpg
    2016_Romania:
      name: "Romania"
      date: "2017/01/01"
      best_image: 0032.jpg