
title: Daniel Andrade Photo Gallery
email: daniel@danielandrade.net
description: >- # this means to ignore newlines until "baseurl:"
  My own little photo gallery
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://amanabt.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dspillere
github_username:  dansku

exclude: [node_modules, Gemfile, Gemfile.lock, gulpfile.js, deploy.sh, README.md, index.md, .gitignore]

#--------------------------------------------
gallery:
  dir: photos
  title: "Photos"
  sort_field: "date"
  title_prefix: "" 
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  thumbnail_size:
    y: 450
    retina: 1.5
    
  # The following options are for individual galleries.
gallery:
  dir: photos
  title: "Photos"
  sort_field: "date"
  thumbnail_size:
    y: 450
    retina: 1.5
  galleries:
    nainital_trip:
      name: "Nainital Trekking"
      date: "2018/03/18"
      best_image: 20190318_143442.jpg
